# Generated by Django 2.1.7 on 2021-08-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('surplus_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Weekly')),
                ('surplus_bi_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus BeWeekly')),
                ('surplus_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Monthly')),
                ('surplus_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Surplus Yearly')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('c_type', models.IntegerField(choices=[(1, 'INCOME'), (2, 'EXPENSE'), (3, 'OTHERS')], default=3, verbose_name='Type')),
                ('persistent', models.BooleanField(default=False, verbose_name='Persistent')),
                ('total_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Weekly')),
                ('total_bi_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Bi Weekly')),
                ('total_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Monthly')),
                ('total_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Total Yearly')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Weekly Net')),
                ('bi_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Bi Weekly Net')),
                ('monthly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Monthly Net')),
                ('yearly', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Yearly Net')),
                ('ref_category', models.BigIntegerField(blank=True, null=True, verbose_name='Ref Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.Category')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='budget.Category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_budgets', to='budget.Category'),
        ),
    ]
