# Generated by Django 2.1.7 on 2021-08-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='budget.Category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_budgets', to='budget.Category'),
        ),
    ]
