# Generated by Django 2.1.7 on 2021-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_persistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
