# Generated by Django 2.1.7 on 2021-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210821_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pie_title',
            field=models.CharField(default='', max_length=190, verbose_name='Pie Title'),
        ),
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default='', max_length=190, verbose_name='Title'),
        ),
    ]
