# Generated by Django 2.1.7 on 2021-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210825_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='pie_title',
            field=models.CharField(default='Typical Monthly Budget', max_length=190, verbose_name='Pie Title'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(default='Summary of Monthly Budgeted Expenses', max_length=190, verbose_name='Title'),
        ),
    ]
