# Generated by Django 2.1.7 on 2021-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210825_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='pie_title',
            field=models.CharField(default='', max_length=190, verbose_name='Pie Title'),
        ),
    ]
