# Generated by Django 2.1.7 on 2021-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20210828_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
