# Generated by Django 2.1.7 on 2021-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20210928_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
